name: Quality assurance

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: cs2pr, phpstan, composer:v2

      - name: Install Composer dependencies (highest)
        uses: 'ramsey/composer-install@v1'
        with:
          dependency-versions: 'highest'
          composer-options: '--prefer-dist --prefer-stable'

      - name: PHPStan
        run: phpstan analyse --error-format=checkstyle | cs2pr
