name: Test

on: [push, pull_request ]

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} + ${{ matrix.dependencies }}'
        runs-on: ubuntu-24.04

        strategy:
            fail-fast: false
            matrix:
                dependencies:
                    - lowest
                    - highest
                php-version:
                    - '8.2'
                    - '8.3'
                    - '8.4'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
            - name: 'Install Composer dependencies (${{ matrix.dependencies }})'
              uses: 'ramsey/composer-install@v1'
              with:
                  dependency-versions: '${{ matrix.dependencies }}'
                  composer-options: --prefer-dist --prefer-stable ${{ matrix.php-version == '8.4' && '--ignore-platform-req=php' || '' }}
            - name: Run Tests
              run: composer test
